### ISSUE TITLE
Trouble running mmvec/Tensorflow

### ISSUE THREAD

**Issue by CarlaCristinaUranga** [biocore/mmvec#150]
Hi,

I am on an institutional computer, in case this is the issue, but I am not able to run mmvec on my computer. I am totally new to this plugin so please forgive me if this is an obvious issue. When using the qiime2 mmvec plug in, I use the following command:

qiime mmvec paired-omics \
        --i-microbes OTU16s.qza \
        --i-metabolites OTUprot.qza \
        --p-learning-rate 1e-3 \
        --o-conditionals ranks.qza \
        --o-conditional-biplot biplot.qza

However, I get this error (thank you in advance!):

Traceback (most recent call last):
  File "/Users/curanga/opt/anaconda3/envs/qiime2-2020.8/bin/qiime", line 11, in <module>
    sys.exit(qiime())
  File "/Users/curanga/opt/anaconda3/envs/qiime2-2020.8/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/curanga/opt/anaconda3/envs/qiime2-2020.8/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/curanga/opt/anaconda3/envs/qiime2-2020.8/lib/python3.6/site-packages/click/core.py", line 1254, in invoke
    cmd_name, cmd, args = self.resolve_command(ctx, args)
  File "/Users/curanga/opt/anaconda3/envs/qiime2-2020.8/lib/python3.6/site-packages/click/core.py", line 1297, in resolve_command
    cmd = self.get_command(ctx, cmd_name)
  File "/Users/curanga/opt/anaconda3/envs/qiime2-2020.8/lib/python3.6/site-packages/q2cli/commands.py", line 100, in get_command
    plugin = self._plugin_lookup[name]
  File "/Users/curanga/opt/anaconda3/envs/qiime2-2020.8/lib/python3.6/site-packages/q2cli/commands.py", line 76, in _plugin_lookup
    import q2cli.core.cache
  File "/Users/curanga/opt/anaconda3/envs/qiime2-2020.8/lib/python3.6/site-packages/q2cli/core/cache.py", line 406, in <module>
    CACHE = DeploymentCache()
  File "/Users/curanga/opt/anaconda3/envs/qiime2-2020.8/lib/python3.6/site-packages/q2cli/core/cache.py", line 61, in __init__
    self._state = self._get_cached_state(refresh=refresh)
  File "/Users/curanga/opt/anaconda3/envs/qiime2-2020.8/lib/python3.6/site-packages/q2cli/core/cache.py", line 107, in _get_cached_state
    self._cache_current_state(current_requirements)
  File "/Users/curanga/opt/anaconda3/envs/qiime2-2020.8/lib/python3.6/site-packages/q2cli/core/cache.py", line 200, in _cache_current_state
    state = self._get_current_state()
  File "/Users/curanga/opt/anaconda3/envs/qiime2-2020.8/lib/python3.6/site-packages/q2cli/core/cache.py", line 238, in _get_current_state
    plugin_manager = qiime2.sdk.PluginManager()
  File "/Users/curanga/opt/anaconda3/envs/qiime2-2020.8/lib/python3.6/site-packages/qiime2/sdk/plugin_manager.py", line 54, in __new__
    self._init(add_plugins=add_plugins)
  File "/Users/curanga/opt/anaconda3/envs/qiime2-2020.8/lib/python3.6/site-packages/qiime2/sdk/plugin_manager.py", line 81, in _init
    plugin = entry_point.load()
  File "/Users/curanga/opt/anaconda3/envs/qiime2-2020.8/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2471, in load
    self.require(*args, **kwargs)
  File "/Users/curanga/opt/anaconda3/envs/qiime2-2020.8/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2494, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/Users/curanga/opt/anaconda3/envs/qiime2-2020.8/lib/python3.6/site-packages/pkg_resources/__init__.py", line 790, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (tensorflow-estimator 2.2.0 (/Users/curanga/opt/anaconda3/envs/qiime2-2020.8/lib/python3.6/site-packages), Requirement.parse('tensorflow-estimator==1.15.1'), {'tensorflow'})

**Comment by mortonjt** [comment]
Hi, it looks like you have tensorflow2 instead, which MMvec is not
compatible with.  It is recommended to downgrade to tensorflow=1.15.
You may have to either run this in an older qiime2 environment <2020.6, or
install a separate conda environment with the standalone version.

**Comment by CarlaCristinaUranga** [comment]
Wow thank you for your fast reply! I am having trouble with the standalone version. I would love to use the standalone version, but I get this error:

Traceback (most recent call last):
  File "/Users/curanga/opt/anaconda3/envs/mmvec/bin/mmvec", line 17, in <module>
    import tensorflow as tf
  File "/Users/curanga/opt/anaconda3/envs/mmvec/lib/python3.7/site-packages/tensorflow/__init__.py", line 99, in <module>
    from tensorflow_core import *
  File "/Users/curanga/opt/anaconda3/envs/mmvec/lib/python3.7/site-packages/tensorflow_core/__init__.py", line 36, in <module>
    from tensorflow._api.v1 import compat
  File "/Users/curanga/opt/anaconda3/envs/mmvec/lib/python3.7/site-packages/tensorflow_core/_api/v1/compat/__init__.py", line 23, in <module>
    from tensorflow._api.v1.compat import v1
  File "/Users/curanga/opt/anaconda3/envs/mmvec/lib/python3.7/site-packages/tensorflow_core/_api/v1/compat/v1/__init__.py", line 672, in <module>
    from tensorflow_estimator.python.estimator.api._v1 import estimator
  File "/Users/curanga/opt/anaconda3/envs/mmvec/lib/python3.7/site-packages/tensorflow_estimator/__init__.py", line 10, in <module>
    from tensorflow_estimator._api.v1 import estimator
  File "/Users/curanga/opt/anaconda3/envs/mmvec/lib/python3.7/site-packages/tensorflow_estimator/_api/v1/estimator/__init__.py", line 10, in <module>
    from tensorflow_estimator._api.v1.estimator import experimental
  File "/Users/curanga/opt/anaconda3/envs/mmvec/lib/python3.7/site-packages/tensorflow_estimator/_api/v1/estimator/experimental/__init__.py", line 10, in <module>
    from tensorflow_estimator.python.estimator.canned.dnn import dnn_logit_fn_builder
  File "/Users/curanga/opt/anaconda3/envs/mmvec/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/canned/dnn.py", line 33, in <module>
    from tensorflow_estimator.python.estimator import estimator
  File "/Users/curanga/opt/anaconda3/envs/mmvec/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 53, in <module>
    from tensorflow_estimator.python.estimator import util as estimator_util
  File "/Users/curanga/opt/anaconda3/envs/mmvec/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/util.py", line 75, in <module>
    class _DatasetInitializerHook(tf.compat.v1.train.SessionRunHook):
AttributeError: module 'tensorflow' has no attribute 'compat'

**Comment by mortonjt** [comment]
Something is weird with the install - did you use pip or conda?  Did you
create a separate conda environment as outlined in the readme?

**Comment by CarlaCristinaUranga** [comment]
Hi so I started with a fresh install using pip install mmvec and this is the output:

(base) mgardnerlt-osx:FINAL_PROTEOMICS curanga$ mmvec paired-omics \
>         --microbe-file OTU16s.biom \
>         --metabolite-file OTUprot.biom \
>         --summary-dir summary
/Users/curanga/opt/anaconda3/lib/python3.7/site-packages/biom_format-2.1.8.dev0-py3.7-macosx-10.9-x86_64.egg/biom/table.py:4068: FutureWarning: SparseDataFrame is deprecated and will be removed in a future version.
Use a regular DataFrame whose columns are SparseArrays instead.

See http://pandas.pydata.org/pandas-docs/stable/user_guide/sparse.html#migrating for more.

  return constructor(mat, index=index, columns=columns)
/Users/curanga/opt/anaconda3/lib/python3.7/site-packages/pandas/core/sparse/frame.py:257: FutureWarning: SparseSeries is deprecated and will be removed in a future version.
Use a Series with sparse values instead.

    >>> series = pd.Series(pd.SparseArray(...))

See http://pandas.pydata.org/pandas-docs/stable/user_guide/sparse.html#migrating for more.

  sparse_index=BlockIndex(N, blocs, blens),
/Users/curanga/opt/anaconda3/lib/python3.7/site-packages/pandas/core/generic.py:4583: FutureWarning: SparseSeries is deprecated and will be removed in a future version.
Use a Series with sparse values instead.

    >>> series = pd.Series(pd.SparseArray(...))

See http://pandas.pydata.org/pandas-docs/stable/user_guide/sparse.html#migrating for more.

  return self._constructor(new_data).__finalize__(self)
/Users/curanga/opt/anaconda3/lib/python3.7/site-packages/pandas/core/sparse/frame.py:854: FutureWarning: SparseDataFrame is deprecated and will be removed in a future version.
Use a regular DataFrame whose columns are SparseArrays instead.

See http://pandas.pydata.org/pandas-docs/stable/user_guide/sparse.html#migrating for more.

  default_kind=self._default_kind,
/Users/curanga/opt/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py:3471: FutureWarning: SparseSeries is deprecated and will be removed in a future version.
Use a Series with sparse values instead.

    >>> series = pd.Series(pd.SparseArray(...))

See http://pandas.pydata.org/pandas-docs/stable/user_guide/sparse.html#migrating for more.

  return klass(values, index=self.index, name=items, fastpath=True)
/Users/curanga/opt/anaconda3/lib/python3.7/site-packages/pandas/core/sparse/frame.py:785: FutureWarning: SparseDataFrame is deprecated and will be removed in a future version.
Use a regular DataFrame whose columns are SparseArrays instead.

See http://pandas.pydata.org/pandas-docs/stable/user_guide/sparse.html#migrating for more.

  return self._constructor(new_arrays, index=index, columns=columns).__finalize__(
/Users/curanga/opt/anaconda3/lib/python3.7/site-packages/pandas/core/ops/__init__.py:1641: FutureWarning: SparseSeries is deprecated and will be removed in a future version.
Use a Series with sparse values instead.

    >>> series = pd.Series(pd.SparseArray(...))

See http://pandas.pydata.org/pandas-docs/stable/user_guide/sparse.html#migrating for more.

  return self._constructor(new_values, index=self.index, name=self.name)
/Users/curanga/opt/anaconda3/lib/python3.7/site-packages/pandas/core/sparse/frame.py:339: FutureWarning: SparseDataFrame is deprecated and will be removed in a future version.
Use a regular DataFrame whose columns are SparseArrays instead.

See http://pandas.pydata.org/pandas-docs/stable/user_guide/sparse.html#migrating for more.

  default_fill_value=self.default_fill_value,
/Users/curanga/opt/anaconda3/lib/python3.7/site-packages/pandas/core/generic.py:6289: FutureWarning: SparseDataFrame is deprecated and will be removed in a future version.
Use a regular DataFrame whose columns are SparseArrays instead.

See http://pandas.pydata.org/pandas-docs/stable/user_guide/sparse.html#migrating for more.

  return self._constructor(new_data).__finalize__(self)
/Users/curanga/opt/anaconda3/lib/python3.7/site-packages/pandas/core/generic.py:5884: FutureWarning: SparseSeries is deprecated and will be removed in a future version.
Use a Series with sparse values instead.

    >>> series = pd.Series(pd.SparseArray(...))

See http://pandas.pydata.org/pandas-docs/stable/user_guide/sparse.html#migrating for more.

  return self._constructor(new_data).__finalize__(self)
/Users/curanga/opt/anaconda3/lib/python3.7/site-packages/pandas/core/generic.py:3606: FutureWarning: SparseDataFrame is deprecated and will be removed in a future version.
Use a regular DataFrame whose columns are SparseArrays instead.

See http://pandas.pydata.org/pandas-docs/stable/user_guide/sparse.html#migrating for more.

  result = self._constructor(new_data).__finalize__(self)
WARNING:tensorflow:From /Users/curanga/opt/anaconda3/bin/mmvec:160: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.

WARNING:tensorflow:From /Users/curanga/opt/anaconda3/bin/mmvec:161: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

2020-10-19 21:58:19.943709: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-10-19 21:58:19.976740: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7f9a5b7428b0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-10-19 21:58:19.976759: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
WARNING:tensorflow:From /Users/curanga/opt/anaconda3/lib/python3.7/site-packages/mmvec/multimodal.py:90: The name tf.log is deprecated. Please use tf.math.log instead.

WARNING:tensorflow:From /Users/curanga/opt/anaconda3/lib/python3.7/site-packages/mmvec/multimodal.py:91: multinomial (from tensorflow.python.ops.random_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.random.categorical` instead.
WARNING:tensorflow:From /Users/curanga/opt/anaconda3/lib/python3.7/site-packages/mmvec/multimodal.py:102: The name tf.random_normal is deprecated. Please use tf.random.normal instead.

WARNING:tensorflow:From /Users/curanga/opt/anaconda3/lib/python3.7/site-packages/mmvec/multimodal.py:118: Normal.__init__ (from tensorflow.python.ops.distributions.normal) is deprecated and will be removed after 2019-01-01.
Instructions for updating:
The TensorFlow Distributions library has moved to TensorFlow Probability (https://github.com/tensorflow/probability). You should update all references to use `tfp.distributions` instead of `tf.distributions`.
WARNING:tensorflow:From /Users/curanga/opt/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/ops/distributions/normal.py:160: Distribution.__init__ (from tensorflow.python.ops.distributions.distribution) is deprecated and will be removed after 2019-01-01.
Instructions for updating:
The TensorFlow Distributions library has moved to TensorFlow Probability (https://github.com/tensorflow/probability). You should update all references to use `tfp.distributions` instead of `tf.distributions`.
WARNING:tensorflow:From /Users/curanga/opt/anaconda3/lib/python3.7/site-packages/mmvec/multimodal.py:135: Multinomial.__init__ (from tensorflow.python.ops.distributions.multinomial) is deprecated and will be removed after 2019-01-01.
Instructions for updating:
The TensorFlow Distributions library has moved to TensorFlow Probability (https://github.com/tensorflow/probability). You should update all references to use `tfp.distributions` instead of `tf.distributions`.
WARNING:tensorflow:From /Users/curanga/opt/anaconda3/lib/python3.7/site-packages/mmvec/multimodal.py:183: The name tf.summary.scalar is deprecated. Please use tf.compat.v1.summary.scalar instead.

WARNING:tensorflow:From /Users/curanga/opt/anaconda3/lib/python3.7/site-packages/mmvec/multimodal.py:185: The name tf.summary.histogram is deprecated. Please use tf.compat.v1.summary.histogram instead.

WARNING:tensorflow:From /Users/curanga/opt/anaconda3/lib/python3.7/site-packages/mmvec/multimodal.py:189: The name tf.summary.merge_all is deprecated. Please use tf.compat.v1.summary.merge_all instead.

WARNING:tensorflow:From /Users/curanga/opt/anaconda3/lib/python3.7/site-packages/mmvec/multimodal.py:191: The name tf.summary.FileWriter is deprecated. Please use tf.compat.v1.summary.FileWriter instead.

WARNING:tensorflow:From /Users/curanga/opt/anaconda3/lib/python3.7/site-packages/mmvec/multimodal.py:196: The name tf.train.AdamOptimizer is deprecated. Please use tf.compat.v1.train.AdamOptimizer instead.

WARNING:tensorflow:From /Users/curanga/opt/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/ops/clip_ops.py:301: where (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
WARNING:tensorflow:From /Users/curanga/opt/anaconda3/lib/python3.7/site-packages/mmvec/multimodal.py:206: The name tf.global_variables_initializer is deprecated. Please use tf.compat.v1.global_variables_initializer instead.

WARNING:tensorflow:From /Users/curanga/opt/anaconda3/lib/python3.7/site-packages/mmvec/multimodal.py:243: The name tf.train.Saver is deprecated. Please use tf.compat.v1.train.Saver instead.

0it [00:00, ?it/s]
Traceback (most recent call last):
  File "/Users/curanga/opt/anaconda3/bin/mmvec", line 233, in <module>
    mmvec()
  File "/Users/curanga/opt/anaconda3/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/curanga/opt/anaconda3/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/curanga/opt/anaconda3/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/curanga/opt/anaconda3/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/curanga/opt/anaconda3/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/curanga/opt/anaconda3/bin/mmvec", line 176, in paired_omics
    checkpoint_interval=checkpoint_interval)
  File "/Users/curanga/opt/anaconda3/lib/python3.7/site-packages/mmvec/multimodal.py", line 274, in fit
    self.U = rU
UnboundLocalError: local variable 'rU' referenced before assignment

**Comment by mortonjt** [comment]
ok cool. So it looks like you are able to get something installed :)
Now it seems to be more of a problem of running it.  This type of error occurs when everything gets filtered out.
This can occur for extremely small sample sizes (the min-feature-count is default 10, if you have less than 10 samples MMvec will have problems).

**Comment by CarlaCristinaUranga** [comment]
Ugh really? I have 9 samples! Bummer! So do you have any suggestions for
how to deal with small datasets? This is a huge problem! Thank you for your
honesty.

Best,
Carla

**Comment by mortonjt** [comment]
sorry, we can't do much with 9 samples with mmvec.  I actually don't know of any program that can currently do it, with the exception of highly customized Bayesian inference.  The tricky thing with small datasets is you basically need to know the exact answer ahead of time, and are using the data just to verify if your answer is correct.

**Comment by CarlaCristinaUranga** [comment]
Ok, thank you! Well, using qiime2-2020.6 I get this error, is it also due
to the small dataset?:


(qiime2-2020.6) mgardnerlt-osx:FINAL_PROTEOMICS curanga$ qiime mmvec
paired-omics \

>         --i-microbes OTU16s.qza \

>         --i-metabolites OTUprot.qza \

>         --p-learning-rate 1e-3 \

>         --o-conditionals ranks.qza \

>         --o-conditional-biplot biplot.qza

*Plugin error from mmvec:*


*  local variable 'rU' referenced before assignment*


*Debug info has been saved to
/var/folders/_9/dvqyx4xcx3wwstdv74lh0xw00003ms/T/qiime2-q2cli-err-o96m83cq.log*

**Comment by mortonjt** [comment]
yes, its the same error.

**Comment by CarlaCristinaUranga** [comment]
Ok, I will research other options for co-occurrence analysis for small
datasets. No more mmvec for me right now. Thank you Jamie you are very much
appreciated.

Best wishes,
Carla
