### ISSUE TITLE
ImportError: google/protobuf/pyext/_message.cpython

### ISSUE THREAD

**Issue by tseemann** [biocore/mmvec#48]
Any ideas on why the minaconda install failed?

```
rhapsody  -h
Traceback (most recent call last):
  File "/home/linuxbrew/miniconda3/envs/rhapsody/bin/rhapsody", line 15, in <module>
    import tensorflow as tf
  File "/home/linuxbrew/miniconda3/envs/rhapsody/lib/python3.5/site-packages/tensorflow/__init__.py", line 22, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/home/linuxbrew/miniconda3/envs/rhapsody/lib/python3.5/site-packages/tensorflow/python/__init__.py", line 52, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "/home/linuxbrew/miniconda3/envs/rhapsody/lib/python3.5/site-packages/tensorflow/core/framework/graph_pb2.py", line 6, in <module>
    from google.protobuf import descriptor as _descriptor
  File "/home/linuxbrew/miniconda3/envs/rhapsody/lib/python3.5/site-packages/google/protobuf/descriptor.py", line 47, in <module>
    from google.protobuf.pyext import _message
ImportError: /home/linuxbrew/miniconda3/envs/rhapsody/lib/python3.5/site-packages/google/protobuf/pyext/_message.cpython-35m-x86_64-linux-gnu.so: undefined symbol: _ZNK6google8protobuf10TextFormat17FieldValuePrinter9PrintBoolEb
```

**Comment by mortonjt** [comment]
hmm . It is possible that the conda-forge install of tensorflow is dated.
May want to do `conda install tensorflow -c defaults"` instead.

**Comment by mortonjt** [comment]
@tseemann , rhapsody is now on conda-forge, and the README has been updated.  The following install command should work.

```
conda create -n rhapsody_env rhapsody -c conda-forge
```

**Comment by mortonjt** [comment]
@tseemann , I'm not able to reproduce your error.  There has been a new version on conda-forge that can be installed as follows

```
conda install mmvec -c conda-forge
```

Please reopen if these issues persist.
